const PRODUCT_NAMES = {
  "SMKAP S -001": "Sofa Aria",
  "SMKAP S -002": "Sofa Brielle",
  "SMKAP S -003": "Sofa Camille",
  "SMKAP S -004": "Sofa Daphne",
  "SMKAP S -005": "Sofa Elara",
  "SMKAP S -006": "Sofa Fernanda",
  "SMKAP S -007": "Sofa Giselle",
  "SMKAP S -008": "Sofa Hazel",
  "SMKAP S -009": "Sofa Isla",
  "SMKAP S -010": "Sofa Jasmine",
  "SMKAP S -011": "Sofa Kaia",
  "SMKAP S -012": "Sofa Layla",
  "SMKAP S -013": "Sofa Maeve",
  "SMKAP S -014": "Sofa Noor",
  "SMKAP S -015": "Sofa Opal",
  "SMKAP S -016": "Sofa Priya",
  "SMKAP S -017": "Sofa Quinn",
  "SMKAP S -018": "Sofa Rosalie",
  "SMKAP S -019": "Sofa Sable",
  "SMKAP S -020": "Sofa Tessa",
  "SMKAP S -021": "Sofa Uma",
  "SMKAP S -022": "Sofa Vivienne",
  "SMKAP S -023": "Sofa Willow",
  "SMKAP S -024": "Sofa Ximena",
  "SMKAP S -025": "Sofa Yara",
  "SMKAP S -026": "Sofa Zara",
  "SMKAP S -027": "Sofa Ada",
  "SMKAP LS 001": "Lounge Seating Atlas",
  "SMKAP LS 002": "Lounge Seating Beacon",
  "SMKAP LS 003": "Lounge Seating Cove",
  "SMKAP LS 004": "Lounge Seating Dune",
  "SMKAP LS 005": "Lounge Seating Ember",
  "SMKAP LS 006": "Lounge Seating Fjord",
  "SMKAP LS 007": "Lounge Seating Glade",
  "SMKAP LS 008": "Lounge Seating Harbor",
  "SMKAP LS 009": "Lounge Seating Ivory",
  "SMKAP LS 010": "Lounge Seating Juniper",
  "SMKAP LS 011": "Lounge Seating Kepler",
  "SMKAP LS 012": "Lounge Seating Lagoon",
  "SMKAP LS 013": "Lounge Seating Meridian",
  "SMKAP LS 014": "Lounge Seating Nimbus",
  "SMKAP LS 015": "Lounge Seating Orion",
  "SMKAP LS 016": "Lounge Seating Palisade",
  "SMKAP LS 017": "Lounge Seating Quarry",
  "SMKAP LS 018": "Lounge Seating Ripple",
  "SMKAP LS 019": "Lounge Seating Sienna",
  "SMKAP LS 020": "Lounge Seating Terra",
  "SMKAP LS 021": "Lounge Seating Umbra",
  "SMKAP LS 022": "Lounge Seating Vale",
  "SMKAP LS 023": "Lounge Seating Willowmere",
  "SMKAP LS 024": "Lounge Seating Xanadu",
  "SMKAP LS 025": "Lounge Seating Yosemite",
  "SMKAP LS 026": "Lounge Seating Zenith",
  "SMKAP LS 027": "Lounge Seating Acacia",
  "SMKAP LS 028": "Lounge Seating Boreal",
  "SMKAP LS 029": "Lounge Seating Citrine",
  "SMKAP LS 030": "Lounge Seating Dawnfall",
  "SMKAP LS 031": "Lounge Seating Eclipse",
  "SMKAP LS 032": "Lounge Seating Farallon",
  "SMKAP LS 033": "Lounge Seating Granite",
  "SMKAP LS 034": "Lounge Seating Hearth",
  "SMKAP LS 035": "Lounge Seating Indigo",
  "SMKAP LS 036": "Lounge Seating Jade",
  "SMKAP LS 037": "Lounge Seating Kestrel",
  "SMKAP LS 038": "Lounge Seating Lorien",
  "SMKAP LS 039": "Lounge Seating Mirage",
  "SMKAP WC 003": "Wooden Chair Alba",
  "SMKAP WC 004": "Wooden Chair Birch",
  "SMKAP WC 005": "Wooden Chair Cedar",
  "SMKAP WC 006": "Wooden Chair Dover",
  "SMKAP WC 007": "Wooden Chair Elm",
  "SMKAP WC 008": "Wooden Chair Fenwick",
  "SMKAP WC 009": "Wooden Chair Grove",
  "SMKAP WC 010": "Wooden Chair Holly",
  "SMKAP WC 011": "Wooden Chair Iverson",
  "SMKAP WC 012": "Wooden Chair Juniper",
  "SMKAP WC 013": "Wooden Chair Kestrel",
  "SMKAP WC 014": "Wooden Chair Linden",
  "SMKAP WC 015": "Wooden Chair Marsh",
  "SMKAP WC 016": "Wooden Chair Noble",
  "SMKAP WC 017": "Wooden Chair Oakley",
  "SMKAP WC 018": "Wooden Chair Pinecrest",
  "SMKAP WC 019": "Wooden Chair Rowan",
  "SMKAP WC 020": "Wooden Chair Saffron",
  "SMKAP WC 021": "Wooden Chair Tansy",
  "SMKAP MC 001": "Metal Chair Steel",
  "SMKAP MC 002": "Metal Chair Aster",
  "SMKAP MC 003": "Metal Chair Cobalt",
  "SMKAP MC 004": "Metal Chair Dusk",
  "SMKAP MC 005": "Metal Chair Forge",
  "SMKAP MC 006": "Metal Chair Helix",
  "SMKAP CS 001": "Café Sofa Bistro",
  "SMKAP CS 002": "Café Sofa Café",
  "SMKAP CS 003": "Café Sofa Croissant",
  "SMKAP CS 004": "Café Sofa Deux",
  "SMKAP CS 005": "Café Sofa Étoile",
  "SMKAP CS 006": "Café Sofa Flâneur",
  "SMKAP-BS-001": "Booth Seating Amber",
  "SMKAP-BS-002": "Booth Seating Bourbon",
  "SMKAP-BS-003": "Booth Seating Cedar",
  "SMKAP-BS-004": "Booth Seating Dartmouth",
  "SMKAP-BS-005": "Booth Seating Ellery",
  "SMKAP-BS-006": "Booth Seating Fletching",
  "SMKAP-BS-007": "Booth Seating Garland",
  "SMKAP-BS-008": "Booth Seating Halcyon",
  "SMKAP-BS-009": "Booth Seating Ivy",
  "SMKAP-BS-010": "Booth Seating Jubilee",
  "SMKAP-BS-011": "Booth Seating Kingsley",
  "SMKAP PU 001": "Puffee Cloud",
  "SMKAP PU 002": "Puffee Dusk",
  "SMKAP PU 003": "Puffee Eider",
  "SMKAP PU 004": "Puffee Fluff",
  "SMKAP PU 005": "Puffee Gossamer",
  "SMKAP PU 006": "Puffee Halo",
  "SMKAP PU 007": "Puffee Isobel",
  "SMKAP PU 008": "Puffee Jupiter",
  "SMKAP PU 009": "Puffee Kumari",
  "SMKAP PU 010": "Puffee Luna",
  "SMKAP PU 011": "Puffee Mistral",
  "SMKAP PU 012": "Puffee Nova",
  "SMKAP CT 001": "Coffee Table Alder",
  "SMKAP CT 002": "Coffee Table Briar",
  "SMKAP CT 003": "Coffee Table Cypress",
  "SMKAP CT 004": "Coffee Table Dawn",
  "SMKAP CT 005": "Coffee Table Ember",
  "SMKAP CT 006": "Coffee Table Fern",
  "SMKAP CT 007": "Coffee Table Granite",
  "SMKAP CT 008": "Coffee Table Haven",
  "SMKAP CT 009": "Coffee Table Indra",
  "SMKAP CT 010": "Coffee Table Jade",
  "SMKAP CT 011": "Coffee Table Kite",
  "SMKAP CT 012": "Coffee Table Lotus",
  "SMKAP CT 013": "Coffee Table Marlow",
  "SMKAP CT 014": "Coffee Table North",
  "SMKAP CT 015": "Coffee Table Onyx",
  "SMKAP CT 016": "Coffee Table Pearl",
  "SMKAP CT 017": "Coffee Table Quartz",
  "SMKAP CT 018": "Coffee Table Reed",
  "SMKAP CT 019": "Coffee Table Sage",
  "SMKAP CT 020": "Coffee Table Tide",
  "SMKAP CT  021": "Coffee Table Umber",
  "SMKAP CT  022": "Coffee Table Vega",
  "SMKAP CT 023": "Coffee Table Willow",
  "SMKAP CT 024": "Coffee Table Yew",
  "SMKAP CT 025": "Coffee Table Zephyr",
  "SMKAP CT 026": "Coffee Table Avalon",
  "SMKAP CT 027": "Coffee Table Brook",
  "SMKAP CT 028": "Coffee Table Clover",
  "SMKAP CT 029": "Coffee Table Dune",
  "SMKAP CT 030": "Coffee Table Echo",
  "SMKAP CT 031": "Coffee Table Falcon",
  "SMKAP CT 032": "Coffee Table Glen",
  "SMKAP CT 033": "Coffee Table Harbor",
  "SMKAP CT 034": "Coffee Table Iris",
  "SMKAP CT 035": "Coffee Table Juno",
  "SMKAP CT 036": "Coffee Table Kestrel",
  "SMKAP CT 037": "Coffee Table Larch",
  "SMKAP CT 038": "Coffee Table Meadow",
  "SMKAP CT 039": "Coffee Table Nimbus",
  "SMKAP CT 040": "Coffee Table Orchid",
  "SMKAP CT 041": "Coffee Table Pebble",
  "SMKAP CT 042": "Coffee Table Ridge",
  "SMKAP CT 043": "Coffee Table Stone",
  "SMKAP CT 044": "Coffee Table Terra",
  "SMKAP CT 045": "Coffee Table Upland",
  "SMKAP CT 046": "Coffee Table Vale",
  "SMKAP CT 047": "Coffee Table Wren",
  "SMKAP CT 048": "Coffee Table Yarrow",
  "SMKAP CT 049": "Coffee Table Azure",
  "SMKAP CT 050": "Coffee Table Bramble",
  "SMKAP CT 051": "Coffee Table Cinder",
  "SMKAP CT 052": "Coffee Table Delta",
  "SMKAP CT 053": "Coffee Table Estuary",
  "SMKAP CT 054": "Coffee Table Fjord",
  "SMKAP CT 055": "Coffee Table Grove",
  "SMKAP CT 056": "Coffee Table Heather",
  "SMKAP CT 057": "Coffee Table Ivy",
  "SMKAP CT 058": "Coffee Table Juniper",
  "SMKAP CT 060": "Coffee Table Halcyon",
  "SMKAP CT 061": "Coffee Table Lagoon",
  "SMKAP CT 062": "Coffee Table Meridian",
  "SMKAP CT 063": "Coffee Table Nova",
  "SMKAP CT 064": "Coffee Table Opaline",
  "SMKAP CT 069": "Coffee Table Pinnacle",
  "SMKAP CT 070": "Coffee Table Ridgeline",
  "SMKAP CT 071": "Coffee Table Solstice",
  "SMKAP LT 001": "Laptop Table Nomad",
  "SMKAP LT 002": "Laptop Table Portable",
  "SMKAP LT 003": "Laptop Table Voyager",
  "SMKAP MT 001": "Meeting Table Aurelia",
  "SMKAP MT 002": "Meeting Table Barents",
  "SMKAP MT 003": "Meeting Table Caspian",
  "SMKAP MT 004": "Meeting Table Danube",
  "SMKAP MT 005": "Meeting Table Elbe",
  "SMKAP MT 006": "Meeting Table Fjord",
  "SMKAP MT 007": "Meeting Table Ganges",
  "SMKAP MT 008": "Meeting Table Hudson",
  "SMKAP MT 009": "Meeting Table Ionian",
  "SMKAP MT 010": "Meeting Table Jade",
  "SMKAP MT 011": "Meeting Table Kalahari",
  "SMKAP MT 012": "Meeting Table Loire",
  "SMKAP MT 013": "Meeting Table Mekong",
  "SMKAP MT 014": "Meeting Table Nile",
  "SMKAP MT 015": "Meeting Table Orinoco",
  "SMKAP MT 016": "Meeting Table Pacific",
  "SMKAP MT 017": "Meeting Table Quartz",
  "SMKAP MT 018": "Meeting Table Rhine",
  "SMKAP MT 019": "Meeting Table Sahara",
  "SMKAP MT 020": "Meeting Table Tigris",
  "SMKAP MT 021": "Meeting Table Ural",
  "SMKAP MT 022": "Meeting Table Volga",
  "SMKAP MT 023": "Meeting Table Wadi",
  "SMKAP MT 022A": "Meeting Table Xingu",
  "SMKAP MT 023A": "Meeting Table Yangtze",
  "SMKAP MT 024": "Meeting Table Zambezi",
  "SMKAP MT 025": "Meeting Table Arctic",
  "SMKAP MT 026": "Meeting Table Baltic",
  "SMKAP MT 027": "Meeting Table Congo",
  "SMKAP MT 028": "Meeting Table Dalmation",
  "SMKAP MT 029": "Meeting Table Everest",
  "SMKAP MT 030": "Meeting Table Fuji",
  "SMKAP MT 031": "Meeting Table Glacier",
  "SMKAP MT 032": "Meeting Table Himalaya",
  "SMKAP MT 033": "Meeting Table Indus",
  "SMKAP MT 034": "Meeting Table Karakoram",
  "SMKAP MT 035": "Meeting Table Lhotse",
  "SMKAP MT 036": "Meeting Table Monsoon",
  "SMKAP MT 037": "Meeting Table Nubian",
  "SMKAP-BST-015": "Bar Stool Ace",
  "SMKAP-BST-016": "Bar Stool Bronx",
  "SMKAP-BST-017": "Bar Stool Cork",
  "SMKAP-BST-018": "Bar Stool Dublin",
  "SMKAP-BST-019": "Bar Stool Elixir",
  "SMKAP-BST-020": "Bar Stool Fizz",
  "SMKAP-BST-021": "Bar Stool Glen",
  "SMKAP-BST-022": "Bar Stool Hops",
  "SMKAP-BST-023": "Bar Stool Ivy",
  "SMKAP-BST-024": "Bar Stool Julep",
  "SMKAP-BST-025": "Bar Stool Keg",
  "SMKAP BT 001": "Bar Table Amaro",
  "SMKAP BT 002": "Bar Table Brass",
  "SMKAP BT 003": "Bar Table Cognac",
  "SMKAP BT 004": "Bar Table Dram",
  "SMKAP BT 005": "Bar Table Earl",
  "SMKAP BT 006": "Bar Table Firkin",
  "SMKAP BT 007": "Bar Table Gilt",
  "SMKAP BT 008": "Bar Table Hoghead",
  "SMKAP BT 009": "Bar Table Iris",
  "SMKAP BT 010": "Bar Table Jigger",
  "KIRA": "KIRA Chair",
  "KIRA-SET": "KIRA Chairs Set",
};
