/**
 * Room furniture presets for "Replace with" (Drafted-style sets).
 * Loaded from Supabase plan_catalog_presets; this is the offline fallback.
 */

export const DEFAULT_PLAN_CATALOG = [
  {
    id: "cat-bed-suite",
    name: "Bed + nightstands + dresser",
    category: "bedroom",
    rich_icon: "bed",
    width_mm: 1520,
    depth_mm: 2030,
  },
  {
    id: "cat-bath",
    name: "Bath (toilet + shower)",
    category: "bathroom",
    rich_icon: "bathtub",
    width_mm: 760,
    depth_mm: 1700,
  },
  {
    id: "cat-k-counter",
    name: "Kitchen counter + stove",
    category: "kitchen",
    rich_icon: "kitchen_island",
    width_mm: 1400,
    depth_mm: 900,
  },
  {
    id: "cat-k-table",
    name: "Kitchen table (2 chairs)",
    category: "kitchen",
    rich_icon: "dining_table",
    chair_count: 4,
    width_mm: 1200,
    depth_mm: 900,
  },
  {
    id: "cat-dining",
    name: "Dining table (4 chairs)",
    category: "dining",
    rich_icon: "dining_table",
    chair_count: 8,
    width_mm: 2200,
    depth_mm: 1400,
  },
  {
    id: "cat-sofa",
    name: "Living sofa (3-seat)",
    category: "living",
    rich_icon: "sofa_3",
    sofa_seats: 3,
    width_mm: 2200,
    depth_mm: 950,
  },
  {
    id: "cat-loveseat",
    name: "Loveseat (2-seat)",
    category: "living",
    rich_icon: "sofa_2",
    sofa_seats: 2,
    width_mm: 1700,
    depth_mm: 950,
  },
  {
    id: "cat-armchair",
    name: "Armchair (1-seat)",
    category: "living",
    rich_icon: "sofa_1",
    sofa_seats: 1,
    width_mm: 1000,
    depth_mm: 950,
  },
  {
    id: "cat-media",
    name: "TV bench / coffee table",
    category: "living",
    rich_icon: "coffee_table",
    width_mm: 1100,
    depth_mm: 650,
  },
  {
    id: "cat-rug",
    name: "Area rug (living)",
    category: "living",
    rich_icon: "area_rug",
    width_mm: 2800,
    depth_mm: 2200,
  },
  {
    id: "cat-side-table",
    name: "Side table + plant",
    category: "living",
    rich_icon: "side_table",
    side_table_plant: true,
    width_mm: 480,
    depth_mm: 480,
  },
  {
    id: "cat-plant",
    name: "Floor plant",
    category: "living",
    rich_icon: "plant",
    width_mm: 550,
    depth_mm: 550,
  },
  {
    id: "cat-desk",
    name: "Office desk",
    category: "office",
    rich_icon: "desk",
    width_mm: 1400,
    depth_mm: 700,
  },
];
